language: go
go:
- tip
before_script:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get code.google.com/p/go.tools/cmd/cover
script:
- "$HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN"
env:
  global:
    secure: FgUeV1mEfl8AWJYg6Atk8oW5nbiKpfBpEH9X255HGGPCjM2UMUvamLEmX0qzme+lrIL/QiptZIsiVm2anhoB8R/iJ2vVyEHB/bq4k+V3B5zqRhgMSovLg3Z4q8iVs4Iy++FZgz5jUd+WkZGcwslQJ9vWgyLnV7i80DvDiHw5KMM=
