language: go

go:
    - 1.3
before_script:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get code.google.com/p/go.tools/cmd/cover
script:
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
