language: go
go:
- 1.3
before_script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/axw/gocov/gocov
- go get github.com/modocache/gover
- go get github.com/mattn/goveralls
script:
- go test -covermode=count -coverprofile semver.coverprofile
- go test -covermode=count -coverprofile parser.coverprofile ./parser
- gover
- "$HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN"
env:
  global:
    secure: FgUeV1mEfl8AWJYg6Atk8oW5nbiKpfBpEH9X255HGGPCjM2UMUvamLEmX0qzme+lrIL/QiptZIsiVm2anhoB8R/iJ2vVyEHB/bq4k+V3B5zqRhgMSovLg3Z4q8iVs4Iy++FZgz5jUd+WkZGcwslQJ9vWgyLnV7i80DvDiHw5KMM=
